// utils/data.js
export const data = {
  products: [
    {
      id: '1',
      name: 'Pink Polo Shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Marl Polo Shirt',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Slim Fit Polo Shirt',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Orange Polo Shirt',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      id: '5',
      name: '핑크 폴로 셔츠',
      image: '/images/p1.jpg',
      price: 110,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: '멋쟁이들이 입는 셔츠',
    },

    {
      id: '6',
      name: '하늘색 폴로 셔츠',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: '하늘색 폴로 셔츠임',
    },
    {
      id: '7',
      name: '7번 셔츠',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 2,
      numReviews: 10,
      description: '7번 셔츠를 소개합니다',
    },
    {
      id: '8',
      name: '오렌지 셔츠',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: '밝은 느낌을 주는 오렌지셔츠',
    },
  ],
}
